### PR TITLE
[resolves #2445] Workaround CAMEL-12379 Camel closing ddbClient it does

### LINKED ISSUE #2445: Restore AWS credentials for Jenkins builds
A workaround for https://issues.apache.org/jira/browse/CAMEL-12379

### PR DESCRIPTION
**Pull request by ppalaga**
not own

### CODE REVIEW

**Comment by ppalaga** [comment]
@tdiesler I changed this PR so that it disables the cleanup and checks for stale resources

**Comment by oscerd** [comment]
I fixed the problem in camel

Il mar 20 mar 2018, 13:23 Peter Palaga <notifications@github.com> ha
scritto:

**Comment by ppalaga** [comment]
Thanks @oscerd! Your fix works for us. I checked locally.

**Comment by oscerd** [comment]
Thanks for reporting @ppalaga

**Pull request closed without merging**
