### PR TITLE
[resolves #1194] Add support for Camel-NATS

### LINKED ISSUE #1194: Add support for Camel-NATS
I'll provide a PR :-)

### PR DESCRIPTION
**Pull request by oscerd**

### CODE REVIEW

**Comment by tdiesler** [comment]
ok to test

**Comment by oscerd** [comment]
Weird.

**Comment by oscerd** [comment]
Let me know if I'm doing something wrong. Locally the full build works.

**Comment by oscerd** [comment]
Ignore the integration test for the moment, and add a simpler one.

**Pull request merged**
