### PR TITLE
Fix for CNFException when metrics gathering is on - #2078

### PR DESCRIPTION
**Pull request by lechique**
This is a fix for problem described in #2078.

### CODE REVIEW

**Comment by jamesnetherton** [comment]
Thanks for the PR. The file you modified is auto-generated, so your change will be overwritten each time the build runs.

Please modify the camel-metrics component module definition in [this file](https://github.com/wildfly-extras/wildfly-camel/blob/master/feature/pack/etc/smartics/camel-modules.xml). Then run the build and commit the modified files.

**Comment by lechique** [comment]
I've modified the mentioned file and compiled everything this time:) Seems that generated file module.xml is correct.

**Comment by jamesnetherton** [comment]
ok to test

**Comment by jamesnetherton** [comment]
Changes merged. Thanks for contributing :smile:

**Pull request closed without merging**
