### PR TITLE
[resolves #2391] Replace WildFly and WildFly-Camel with variables in …

### LINKED ISSUE #2391: Replace "Wildfly" and "Wildfly-Camel" with variables in AsciiDoc documentation
To allow for the possibility of rebranding in downstream product documentation, it is necessary to use variables for "WildFly" and "WildFly-Camel". I would suggest the following substitutions:
```
WildFly -> {wildfly}
WildFly-Camel -> {wildfly-camel}
```
These variables can then be defined in the main `docs/guide/index.adoc` file, as follows:
```
:wildfly: WildFly
:wildfly-camel: WildFly-Camel
```
And in the downstream product docs, the downstream product names can be used.

### PR DESCRIPTION
**Pull request by fbolton**
…user guide docs. I took some care to avoid replacing text in code examples in the doc, so that they don't get messed up.

### CODE REVIEW

**Comment by jamesnetherton** [comment]
I've not tried to build the documentation with these changes, but presumably we should be providing values for these variables via the maven plugin configuration. See the following example where we do this for some other things:

https://github.com/wildfly-extras/wildfly-camel/blob/master/docs/pom.xml#L57-L62

You can test this by:

```
cd docs
mvn clean package
```

Then open `target/generated-docs/index.html` in a browser to check whether everything appears as expected.

**Comment by fbolton** [comment]
Ok, I'll give that a try (as soon as I get back from my next meeting). Thanks, @jamesnetherton !

**Comment by fbolton** [comment]
@jamesnetherton I updated the `pom.xml` file and the doc looked fine after building with Maven. So I have squashed and pushed the latest changes.

**Comment by jamesnetherton** [comment]
Thanks. This looks good to me.

@tdiesler any comments to add?

**Comment by tdiesler** [comment]
fine with me

**Comment by jamesnetherton** [comment]
ok to test

**Pull request closed without merging**
