### PR TITLE
[resolves #1439] Add support for component google-mail

### LINKED ISSUE #1439: Add support for component google-mail
http://camel.apache.org/googlemail.html

### PR DESCRIPTION
**Pull request by ppalaga**
@tdiesler in the end, the integration tests may be run by a CI. The CI only has to keep a filled in copy of `oauth2-options.properties` [1]. I have one such config ready here and I can share it with you. 

The Gmail API tests are off by default. They have to be activated by `-Pgoogle-api-test`.

[1] https://github.com/wildfly-extras/wildfly-camel/commit/8ef62250e93d62b0582953943a7bd2ae166ce539#diff-026ccaa063bc8adbbefd162536836d0fR22

### CODE REVIEW

**Comment by tdiesler** [comment]
Could you pls always enable the test and remove that profile. We have a number of tests that require certain sysprops or env variables. You can use Assume to skip the test when the env does not provide the required settings. https://github.com/wildfly-extras/wildfly-camel/blob/master/itests/standalone/extra/src/test/java/org/wildfly/camel/test/aws/EC2IntegrationTest.java#L72

**Comment by ppalaga** [comment]
> always enable the test and remove that profile. [...] You can use Assume

Done in 703cb7f

**Comment by tdiesler** [comment]
ok to test

**Comment by tdiesler** [comment]
Jenkins uses ENV properties. See https://fabric8-ci.fusesource.com/view/wildfly-camel/job/wildfly-camel-pullreq/configure

**Comment by ppalaga** [comment]
280daa6 uses environment variables.

**Comment by ppalaga** [comment]
a0e4b79 is rebased on top of the current master and solves the broken pubsub classloading.

**Pull request merged**
