### PR TITLE
#2656 #2655

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by ppalaga** [comment]
42ff357 and b70a310 just changed the commit message to contain the downstream issue IDs.

**Comment by jamesnetherton** [comment]
ok to test

**Comment by ppalaga** [comment]
let me look at the failing tests

**Comment by ppalaga** [comment]
retest this please

**Comment by ppalaga** [comment]
@jamesnetherton "retest this please" does not work anymore?

**Comment by ppalaga** [comment]
@jamesnetherton "retest this please" does not work anymore?

**Pull request merged**
