### PR TITLE
#2343 - Remove JUnit version from project generated by archetype

### PR DESCRIPTION
**Pull request by apupier**
the JUnit version is already managed by the BOM

Signed-off-by: Aurélien Pupier <apupier@redhat.com>

### CODE REVIEW

**Comment by jamesnetherton** [comment]
I have an extremely flaky internet connection today so I'll continue our discussion here....

We should be able to take this further and remove version properties:

```
<version.wildfly.arquillian>
<version.apache.camel>
<version.jboss.arquillian>
```

Dependencies related to these should already be inherited from the BOM import.

Please can you also follow the project commit convention `[resolves #issue number] Some comment`.

**Comment by apupier** [comment]
> Please can you also follow the project commit convention [resolves #issue number] Some comment.

I updated it

> We should be able to take this further and remove version properties:
> 
> <version.wildfly.arquillian>
> <version.apache.camel>
> <version.jboss.arquillian>

effectively it seems to be working when i remove them.
I will provide an additional commit to get rid of them

**Comment by jamesnetherton** [comment]
Thanks!

Do you mind squashing up those commits. This project is a little quirky in that the build does the merge instead of the GitHub merge button. So it needs things pre-squashed.

**Comment by jamesnetherton** [comment]
ok to test

**Comment by jamesnetherton** [comment]
retest this please

**Pull request merged**
