### PR TITLE
 #2672 initial JDK11 support

### PR DESCRIPTION
**Pull request by ffang**

### CODE REVIEW

**Comment by ffang** [comment]
I have some initial work about JDK11 support.

So far I got "mvn clean install" passed with OpenJDK11(only ContextTrackerRegistryTest failed with JDK11), but the default profile invoked with "mvn clean install" not run full test suite.
If I use "mvn clean install -Dts.all" I can see dozens of test failures.

**Comment by ppalaga** [comment]
@ffang thankd for the effort! Are you (a) looking for a guidance how to fix the failing tests or (b) you prefer somebody else to take this over?

**Comment by ppalaga** [comment]
OK, taking over.

**Comment by ppalaga** [comment]
Closing this one. My working branch is here: https://github.com/ppalaga/wildfly-camel/tree/i2672

**Pull request closed without merging**
