### PR TITLE
[resolves #1048] Add support for camel-braintree

### LINKED ISSUE #1048: Add support for camel-braintree
Ref [ENTESB-4664](https://issues.jboss.org/browse/ENTESB-4664)

### PR DESCRIPTION
**Pull request by tdiesler**

### CODE REVIEW

**Comment by tdiesler** [comment]
retest this please

**Comment by tdiesler** [comment]
retest this please

**Comment by tdiesler** [comment]
retest this please

**Comment by jamesnetherton** [comment]
retest this please

**Pull request merged**
