### PR TITLE
[CAMEL-8349] Context should be started with defined TCCL

### PR DESCRIPTION
**Pull request by tdiesler**

### CODE REVIEW

**Comment by tdiesler** [comment]
retest this please

**Comment by tdiesler** [comment]
retest this please

**Comment by tdiesler** [comment]
retest this please

**Comment by tdiesler** [comment]
retest this please

**Comment by tdiesler** [comment]
retest this please

**Comment by tdiesler** [comment]
retest this please

**Comment by tdiesler** [comment]
retest this please

**Comment by jamesnetherton** [comment]
retest this please

**Comment by jamesnetherton** [comment]
This branch does not build for me locally. Quite a few of the standalone integration tests fail with missing dependencies. Specifically:

```
Caused by: java.lang.Exception: {"JBAS014771: Services with missing/unavailable dependencies" => ["jboss.naming.context.java.module.simple.simple.DefaultJMSConnectionFactory is missing [jboss.naming.context.java.jboss.DefaultJMSConnectionFactory]"]}
```

Although Jenkins is failing elsewhere....

**Pull request merged**
