### PR TITLE
I2412

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by ppalaga** [comment]
@jamesnetherton could you please review?

**Comment by jamesnetherton** [comment]
Happy with the docker change. The roadmap changes are perhaps a result of building with a mix of WFC / Camel versions. E.g component `yql` was added to the unreleased Camel 2.21, so we don't want this on the master branch.

**Comment by ppalaga** [comment]
the iteration ending with 87cf4bb contains no `*.roadmap` changes

**Comment by jamesnetherton** [comment]
ok to test

**Comment by ppalaga** [comment]
retest this please

**Comment by jamesnetherton** [comment]
retest this please

**Pull request merged**
