### PR TITLE
[ENTESB-9964]Camel FTPS throws java.lang.NoClassDefFoundError: javax/net/ssl/SSLException

### PR DESCRIPTION
**Pull request by vkamble60**

### CODE REVIEW

**Comment by vkamble60** [comment]
@jamesnetherton Thank you for correction. Will make appropriate changes in PR.

**Comment by vkamble60** [comment]
@jamesnetherton I have updated pull request. Please check and let me know if there is any thing missing.

**Comment by jamesnetherton** [comment]
@vkamble60 thanks. You also need to run the project build to regenerate the module.xml for camel-ftp. 

So run `mvn clean install` from the project root (note this may take some time) and afterwards you should see some additional files to add to your commit.

**Comment by jamesnetherton** [comment]
@vkamble60 thanks for contributing :+1:

**Pull request closed without merging**
