### PR TITLE
[resolves #1933] NameNotFoundException: infinispan/container/server

### LINKED ISSUE #1933: NameNotFoundException: infinispan/container/server
```
Tests in error: 
  InfinispanIntegrationTest.setUp:67 » NameNotFound infinispan/container/server
  InfinispanIntegrationTest.setUp:67 » NameNotFound infinispan/container/server
  InfinispanIntegrationTest.setUp:67 » NameNotFound infinispan/container/server
  InfinispanIntegrationTest.setUp:67 » NameNotFound infinispan/container/server
  InfinispanIntegrationTest.setUp:67 » NameNotFound infinispan/container/server
  InfinispanIntegrationTest.setUp:67 » NameNotFound infinispan/container/server
  InfinispanIntegrationTest.setUp:67 » NameNotFound infinispan/container/server
```

### PR DESCRIPTION
**Pull request by pferraro**

### CODE REVIEW

**Comment by tdiesler** [comment]
Are you saying that this can only work for webapps?

**Comment by tdiesler** [comment]
merged

**Comment by pferraro** [comment]
@tdiesler This would work with any deployment type whose descriptor can define a resource-ref, e.g. ejb-jar.xml, application.xml, etc.

**Comment by tdiesler** [comment]
@pferraro Sure, and how can we get this to work in a plain jar deployment?

**Comment by pferraro** [comment]
@tdiesler Move the Infinispan cache @Resource injection into a bean within the jar so that the @Resource injection is resolved by the ee subsystem.

**Comment by tdiesler** [comment]
@pferraro Would it work if my deployment installed a service that has a dependency on some infinispan jndi service?

**Pull request closed without merging**
