### PR TITLE
[resolves #1437] Add support for component google-calendar

### LINKED ISSUE #1437: Add support for component google-calendar

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by jamesnetherton** [comment]
@ppalaga If you can resolve the conflicts, we can get this merged ASAP.

All of the Google API credentials are already configured on Jenkins, right?

**Comment by ppalaga** [comment]
000d240 resolves the conflicts.

> All of the Google API credentials are already configured on Jenkins, right?

Yes.

**Comment by ppalaga** [comment]
dea5c32 resolves the conflicts again

**Comment by jamesnetherton** [comment]
ok to test

**Pull request merged**
