### PR TITLE
[resolves #2441] Reject Camel Spring deployments which fail on context startup

### LINKED ISSUE #2441: Reject Camel Spring deployments which fail on context startup
Right now we log a warning and allow the deployment to proceed. This is not consistent with CDI deployments since any errors encountered during Camel Context startup result in a failed deployment.

### PR DESCRIPTION
**Pull request by jamesnetherton**

### CODE REVIEW

**Comment by jamesnetherton** [comment]
retest this please

**Comment by jamesnetherton** [comment]
retest this please

**Comment by zregvart** [comment]
retest this please

**Comment by zregvart** [comment]
retest this please

**Comment by zregvart** [comment]
retest this please

**Comment by zregvart** [comment]
retest this please

**Pull request merged**
